### ISSUE TITLE
'=' Sign is being typed out as '+'

### ISSUE THREAD

**Issue by TobinShields** [slacker69/DuckiesqueUI#1]
I was testing a payload that used a '=' and it was being printed as a '+.' This is especially hard since I was trying to run a bit of PS code that uses variables. 

I took a look at the TypeWriterWindows.cpp and saw some TODOs around using the VK_OEM_PLUS. I am unfortunately not familiar enough with CPP and Windows API to help. Is this something that there might be a solution to? I can see that this might also be a problem for the: { } and ~ characters as well if they all suffer from the same issue.

**Comment by slacker69** [comment]
Yes, thank you. I was shifting on the + key when I should not have been. I forgot to remove the TODOs which I had already fixed with the (*s) = true; statements.

New release is available.
